# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mantavya30@gmail.com
author_name: Mantavyajain30
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: nft-project

